music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns=[
    path('rain/',views.rain,name="rain"),
    path('<int:id>/',views.detail,name="detail"),
    path('list/',views.list,name="list"),
    path('sunny/',views.sunny,name="sunny"),
    path('christmas/',views.christmas,name="christmas"),
    path('midnight/',views.midnight,name="midnight"),
    path('create/',views.create,name="create"),
    path('new/',views.new,name="new"),
    path('<int:id>/delete/',views.delete,name="delete"),
    path('comment/<int:id>/delete/',views.comment_delete,name="comment_delete"),
    path('find/',views.find,name="find"),
  


    
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
import music.views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',music.views.home,name="home"),
    path('music/',include('music.urls')),
   

]

music/models.py
from django.db import models

TYPE_CHOICES = (
    #첫번쨰는 모델에서 받아들이는, 두번째는 실제로 models.py 작성시에 뜨는
    ('rain','비가 오는 날에'),
    ('sunny','봄이 느껴지는 날에'),
    ('christmas','크리스마스의 기분을 느끼고 싶은 날에'),
    ('midnight','조용한 새벽 공기에')
)

class Song(models.Model):
    id = models.AutoField(primary_key=True, null=False)
    songtitle = models.CharField(max_length=30)
    songwriter = models.CharField(max_length=30)
    lyrics = models.TextField()
    writer = models.CharField(null=True,max_length=30)
    recommendation = models.CharField(null=True, max_length=200, choices = TYPE_CHOICES)
    video = models.CharField(null=True,max_length=100000)

    def __str__(self):
        return self.songtitle
    def summary(self):
        return self.lyrics[:300]
    def srtvid(self):
        return self.video[17:]
    def srtsong(self):
        return self.songtitle.lower()[0]
   
        
CHOICE=(
     ('good','추천해요!'),
    ('bad','아쉬워요!')
)
   
EMOJI = (
    ('cat','🐈'),
    ('dog','🐶'),
    ('good','👍🏻'),
    ('happy','😁'),
    ('heart','💜'),
    ('cool','😎')
)
class Comment(models.Model):
    post = models.ForeignKey(Song,null=False,on_delete = models.CASCADE)
    name = models.CharField(max_length=30)
    text = models.TextField()
    opinion = models.CharField(max_length=30, choices = CHOICE)
    icon = models.CharField(max_length=30,null=False, choices = EMOJI)
    def __str__(self):
        if self.opinion=="good":
            return "추천해요!"
        else:
            return "아쉬워요!"

music/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Song
from .models import Comment

def home(request):
    return render(request,'home.html')

#task = recommendation을 기준으로 분류를 하고 싶음. 
def rain(request):
    songs = Song.objects.filter(recommendation="rain")
    return render(request,'rain.html',{'songs':songs})

def detail(request,id):
    song = get_object_or_404(Song,pk=id)
    comments = Comment.objects.filter(post=song)


    if request.method=="POST":
        new_comment = Comment()
        new_comment.post = song
        new_comment.name = request.POST['name']
        new_comment.text = request.POST['text']
        new_comment.opinion = request.POST['opnion']
        new_comment.icon = request.POST['icon']
        new_comment.save()
       
    return render(request,'detail.html',{'song':song,'comments':comments})

def list(request):
    return render(request,'list.html')

def sunny(request):
    songs = Song.objects.filter(recommendation="sunny")
    return render(request,'sunny.html',{'songs':songs})

def christmas(request):
    songs = Song.objects.filter(recommendation="christmas")
    return render(request,'christmas.html',{'songs':songs})

def midnight(request):
    songs = Song.objects.filter(recommendation="midnight")
    return render(request,'midnight.html',{'songs':songs})

def create(request):
    return render(request,'create.html')

def new(request):
    if 'songtitle' and 'songwriter' and 'video' and 'recommendation' and 'lyrics' and 'writer':
        post = Song()
        post.songtitle = request.POST['songtitle']
        post.songwriter = request.POST['songwriter']
        post.video = request.POST['video']
        post.recommendation = request.POST['recommendation']
        post.lyrics = request.POST['lyrics']
        post.writer = request.POST['writer']
        post.save()
        return redirect('music:detail',post.id)
    else:
        return redirect('music:create')

def delete(request,id):
    song = Song.objects.get(pk=id)
    song.delete()
    return redirect('home')

def comment_delete(request,id):
    comment = Comment.objects.get(pk=id)
    comment.delete()
    return redirect('music:detail',comment.post_id)

def find(request):
    songs = Song.objects.all()

    q = request.GET.get('q','')
    if q:
        #q가 있다면 쿼리셋을 생성한다는 의미
        songs = songs.filter(songtitle__icontains=q)
        return render(request,'find.html',{'songs':songs,'q':q})
    else:
        k = "none"
        return render(request,'find.html',{"songs":songs,'k':k})
    

music/templates/christmas.html
{% extends 'base.html' %}
{%block content%}


<h3>&#x1F385;</h3>
<br><br><br>

{% for song in songs %}
<a style="font-size:25px; text-decoration:none;" href="{% url 'music:detail' song.id %}">{{song.songtitle}} - {{song.songwriter}}</a>
<br>
<a id ="lyrics" style="text-decoration:none; font-size:13px;" href="{% url 'music:detail' song.id %}">{{song.summary}}...</a>
<br><br>
{%endfor%}


{% endblock %}

{% comment %} {% url 'song:detail' song.id%} {% endcomment %}

music/templates/create.html
{% extends 'base.html' %}
{% block content%}

<h3 style="text-align:center;">추천하고 싶은 노래를 알려주세요 !</h3>
<br><br><br>
{% comment %} song.id 부분 수정해야할지 보기 ! 일단 views.py 에서 받기는 하기 {% endcomment %}
<form style="text-align:center;"action="{% url 'music:new' %}" method="post">
{% csrf_token %}
<p> 언제 들으면 좋을까요? </p>
<select name="recommendation">
    <option value="none"selected>=== 선택 ===</option>
    <option value="rain" >비가 오는 날에</option>
    <option value="sunny">봄이 느껴지는 날에</option>
    <option value="midnight">조용한 새벽 공기에</option>
    <option value="christmas">크리스마스의 기분을 느끼고 싶은 날에</option>
  </select>
<br><br><br>
<p>노래의 제목은 무엇인가요? </p> 
<input name = "songtitle" type="text">
<br><br><br>
<p>노래를 부른 가수는 누구인가요? </p> 
<input name = "songwriter" type="text">
<br><br><br>
<p>노래의 가사는 무엇인가요? </p> 
<textarea name="lyrics" cols="50" rows="10"></textarea>
<br><br><br>
<p>당신의 닉네임을 알려주세요! </p> 
<input name = "writer" type="text">
<br><br><br>
<p>노래를 들을 수 있는 유튜브 링크를 첨부해주세요. </p> 
<input name = "video" type="text">
<br><br>
<button type="submit">추천하기!</button>


</form>

{% endblock %}

music/templates/detail.html
{% extends 'base.html' %}
{% block content%}


<p> &#x1F3BC;{{song.writer}}님의 추천 </p>
<br><br>
<a href="{% url 'music:list' %}"> 돌아가기 ↩︎</a>
<br><br>
<p style="font-size:30px;">&#x2714; {{song.songtitle}}</p>
<p>{{song.songwriter}}</p>
<p>{{song.lyrics}}</p>

<p>&#x1F3B1; 지금 이 노래, 들어보기 <p>
<iframe width="560" height="315" src="https://youtube.com/embed/{{song.srtvid}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<p> 동영상을 재생할 수 없다고 뜨는 경우는, 해당 유튜브 링크에서 퍼가기를 비허용 한 것입니다.</p>
<p> 감상을 원하신다면, YouTube에서 보기를 클릭하여 감상해주세요 &#x1F3B5;</p>
<br>
<hr>
{% for comment in comments %}

  <p>{{comment.get_icon_display}} {{comment.name}}님의 댓글</p>
  <br>
  {{comment.text}}
<br><br><br>

{% if comment.opinion == 'bad'%}
<p style="font-size:13px; font-style:oblique">- {{comment.name}} 님은 {{song.songtitle}}을(를) 추천하지 않았어요.</p>
{% else %}
<p style="font-size:13px; font-style:oblique">- {{comment.name}} 님은 {{song.songtitle}} 을(를) 추천했어요. </p>
{% endif %}

<a style="float:right; font-size:13px;" href="{% url 'music:comment_delete' comment.id %}">댓글 삭제하기</a>
<br><hr>
{% endfor %}
<br>

<form action="{% url 'music:detail' song.id %}" method="POST">
{%csrf_token%}
<p>당신을 표현하는 이모지는? </p>
<select name="icon">
    <option value="none"selected>=== 선택 ===</option>
    <option value="cat" >🐈</option>
    <option value="dog">🐶</option>
    <option value="good" >👍🏻</option>
    <option value="happy">😁</option>
    <option value="heart" >💜</option>
    <option value="cool">😎</option>

  </select>
<br><br>
<p>닉네임을 알려주세요</p> 
<input name = "name" type="text">
<br><br>
<p>어떤 말을 남기고 싶은가요?</p> 
<textarea name="text" cols="80" rows="3"></textarea>
<br><br><br>
<p>이 노래에 대해서 어떻게 생각하나요?</p> 

<select name="opnion">
    <option value="none"selected>=== 선택 ===</option>
    <option value="good" >추천해요!</option>
    <option value="bad">아쉬워요!</option>
  </select>
 
<button type="submit"> 댓글 등록하기 </button>
</form>
<br><br><br>
<a href="{% url 'music:delete' song.id %}">글 삭제하기</a>
{% endblock %}

music/templates/find.html
{% extends 'base.html' %}
{% block content%}
<div >
{% if not k %}
<p style="text-align:center;color:rgb(115, 174, 222);">{{q}}에 대한 검색 결과입니다. </p>
{% for song in songs %}
{{song.songtitle}} - {{song.songwriter}} 
<p>{{song.summary}}<a href="{% url 'music:detail' song.id %}">...</a></p>
{% endfor%}
{% else%}
<p style="text-align:center;">검색어를 입력하지 않으셨습니다. 다시 검색해주세요.</p>
{% endif %}
<br>




{% endblock %} 

music/templates/home.html
{% extends 'base.html' %}
{%block content%}
<br><br>
<br><br>

<h1>&#x1F3B5;</h1>
<br><br>


what is your taste?
{%endblock%}

music/templates/list.html
{% extends 'base.html' %}
{% block content%}
<h4 ><a style="color:black; text-decoration:none;" href="{% url 'music:rain'%}">&#x2614; 오늘은 비가 오나요?</a></h4>
<br><br>
<h4 ><a style="color:black; text-decoration:none;" href="{% url 'music:sunny'%}">&#x1F337; 봄이 성큼 다가왔나요? </a></h4>
<br><br>
<h4 ><a style="color:black; text-decoration:none;" href="{% url 'music:christmas'%}">&#x1F385; 크리스마스의 분위기를 느끼고 싶은 날인가요? </a></h4>
<br><br>
<h4 ><a style="color:black; text-decoration:none;" href="{% url 'music:midnight'%}">&#x1F303; 새벽의 공기 속에 있나요? </a></h4>
{% endblock %}

music/templates/midnight.html
{% extends 'base.html' %}
{%block content%}


<h3>&#x1F303;</h3>
<br><br><br>

{% for song in songs %}
<a style="font-size:25px; text-decoration:none;" href="{% url 'music:detail' song.id %}">{{song.songtitle}} - {{song.songwriter}}</a>
<br>
<a id ="lyrics" style="text-decoration:none; font-size:13px;" href="{% url 'music:detail' song.id %}">{{song.summary}}...</a>
<br><br>
{%endfor%}



{% endblock %}

{% comment %} {% url 'song:detail' song.id%} {% endcomment %}

music/templates/rain.html
{% extends 'base.html' %}
{%block content%}


<h3>&#x2614;</h3>
<br><br><br>

{% for song in songs %}
<a style="font-size:25px; text-decoration:none;" href="{% url 'music:detail' song.id %}">{{song.songtitle}} - {{song.songwriter}}</a>
<br>
<a id ="lyrics" style="text-decoration:none; font-size:13px;" href="{% url 'music:detail' song.id %}">{{song.summary}}...</a>
<br><br>
{%endfor%}



{% endblock %}

{% comment %} {% url 'song:detail' song.id%} {% endcomment %}

music/templates/search.html
{% extends 'base.html' %}
{% blcok content%}

{% endblock %}

music/templates/song.html
{% extends 'base.html' %}
{%block content%}


<h3>&#x2614;</h3>
<br><br><br>

{% for song in songs %}
<h5>{{song.songtitle}} - {{song.songwriter}}</h5>

<p style="font-size:13px;">{{song.summary}}<a href="{% url 'music:detail' song.id %}">...</a></p>
{%endfor%}

<h3></h3>
{% endblock %}

{% comment %} {% url 'song:detail' song.id%} {% endcomment %}

music/templates/sunny.html
{% extends 'base.html' %}
{%block content%}

<h3>&#x1F337;</h3>
<br><br><br>

{% for song in songs %}
<a  style="font-size:25px; text-decoration:none;" href="{% url 'music:detail' song.id %}">{{song.songtitle}} - {{song.songwriter}}</a>
<br>
<a id ="lyrics" style="text-decoration:none; font-size:13px;" href="{% url 'music:detail' song.id %}">{{song.summary}}...</a>
<br><br>
{%endfor%}


{% endblock %}